name: Publish

on:
  push:
    # branches: main
    branches: main-tmp

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      # - run: pnpm test
      - run: pnpm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
      - run: pnpm publish -r --report-summary --publish-branch main-tmp
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm generate_slack_report
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
